defaults: &defaults
  working_directory: ~/project/repo
  docker:
    - image: circleci/node:latest@sha256:cc685feed1e9ace4451a11b05f9c11ff21fbd051fb0ee810d31ff672e8ee5dc3

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run:
          name: Install Docker client
          command: sudo apt-get install docker
      - run: docker build .

workflows:
  version: 2
  test_and_release:
    jobs:
      - test
