defaults: &defaults
  working_directory: ~/project/repo
  docker:
    - image: circleci/node:latest@sha256:0993d3a2ec640278083cbfe4fed728d15204f131615a2513f1ceb248293afe8d

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run:
          name: Install Docker client
          command: sudo apt-get install docker
      - run: docker build .

workflows:
  version: 2
  test_and_release:
    jobs:
      - test
